[tool.poetry]
name = "pyembree"
version = "0.2.0"
description = "Python wrapper for Intel Embree 2.17.7"
authors = [
    "Anthony Scopatz <scopatz@gmail.com>",
    "Adam Hendry <adam.grant.hendry@gmail.com>"
]
license = "BSD 2-Clause \"Simplified\""
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8"
]
readme = "README.rst"
repository = "https://github.com/adam-grant-hendry/pyembree"
include = [
    { path = "build.py" }
]

[tool.poetry.dependencies]
python = "3.8"
numpy = "^1.22.2"
Cython = "^0.29.28"
setuptools = "^60.9.3"
wheel = "^0.37.1"
trimesh = "^3.10.7"
Rtree = "^1.0.0"

[tool.poetry.dev-dependencies]
pylint = "^2.12.2"
pytest = "^7.0.1"
coverage = "^6.3.2"
ipython = "^8.1.1"
isort = "^5.10.1"
black = "^22.3.0"

[tool.poetry.build]
generate-setup-file = false
script = "build.py"

[build-system]
requires = [
    "Cython",
    "numpy",
    "setuptools>=45",
    "wheel"
]
build-backend = "setuptools.build_meta"